##### !pip install pandas

In [4]:
!pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\t470p\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.23 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\t470p\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

In [5]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\t470p\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\t470p\anaconda3\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in c:\users\t470p\anaconda3\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\t470p\anaconda3\lib\site-packages (from seaborn) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\t470p\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\t470p\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\t470p\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\t470p\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

In [6]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\t470p\anaconda3\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\t470p\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\t470p\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\t470p\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\t470p\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import RandomizedSearchCV
from collections import Counter

In [2]:
import pandas as pd

pd.set_option('display.max_colwidth', None)

In [3]:
dis_sym_data = pd.read_csv(r"Original_Dataset.csv")

In [4]:
dis_sym_data

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
columns_to_check = []
for col in dis_sym_data.columns:
    if col != 'Disease':
        columns_to_check.append(col)

In [6]:
symptoms = dis_sym_data.iloc[:, 1:].values.flatten()
symptoms = list(set(symptoms))

In [7]:
for symptom in symptoms:
    dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(lambda row: int(symptom in row.values), axis=1)

dis_sym_data_v1 = dis_sym_data.drop(columns=columns_to_check)

In [8]:
dis_sym_data_v1 = dis_sym_data_v1.loc[:, dis_sym_data_v1.columns.notna()]

In [8]:
dis_sym_data_v1.shape

(4920, 133)

In [9]:
dis_sym_data_v1.columns = dis_sym_data_v1.columns.str.strip()

In [10]:
dis_sym_data_v1.columns

Index([              'Disease',   'dischromic _patches',
         'visual_disturbances',     'yellow_crust_ooze',
            'internal_itching',      'excessive_hunger',
          'increased_appetite',           'weight_gain',
       'irregular_sugar_level',           'mood_swings',
       ...
                'constipation',             'knee_pain',
                     'itching',  'pain_behind_the_eyes',
             'muscle_weakness',          'restlessness',
                'swollen_legs',          'yellow_urine',
              'muscle_wasting',        'yellowish_skin'],
      dtype='object', length=133)

In [18]:
dis_sym_data_v1.to_csv("Processed_Dataset.csv")

In [11]:
symptom = list(dis_sym_data_v1)
symptom

['Disease',
 'dischromic _patches',
 'visual_disturbances',
 'yellow_crust_ooze',
 'internal_itching',
 'excessive_hunger',
 'increased_appetite',
 'weight_gain',
 'irregular_sugar_level',
 'mood_swings',
 'hip_joint_pain',
 'unsteadiness',
 'abdominal_pain',
 'palpitations',
 'extra_marital_contacts',
 'high_fever',
 'nausea',
 'family_history',
 'skin_rash',
 'stomach_bleeding',
 'cough',
 'spotting_ urination',
 'mucoid_sputum',
 'red_spots_over_body',
 'breathlessness',
 'stomach_pain',
 'small_dents_in_nails',
 'drying_and_tingling_lips',
 'ulcers_on_tongue',
 'bladder_discomfort',
 'watering_from_eyes',
 'coma',
 'lack_of_concentration',
 'obesity',
 'neck_pain',
 'continuous_sneezing',
 'sunken_eyes',
 'weakness_of_one_body_side',
 'distention_of_abdomen',
 'stiff_neck',
 'burning_micturition',
 'blackheads',
 'swollen_extremeties',
 'diarrhoea',
 'painful_walking',
 'indigestion',
 'sweating',
 'muscle_pain',
 'runny_nose',
 'sinus_pressure',
 'swelling_joints',
 'fluid_overload',
 'pain_during_bowel_movements',
 'belly_pain',
 'toxic_look_(typhos)',
 'prominent_veins_on_calf',
 'shivering',
 'rusty_sputum',
 'abnormal_menstruation',
 'back_pain',
 'blurred_and_distorted_vision',
 'headache',
 'cold_hands_and_feets',
 'dark_urine',
 'joint_pain',
 'anxiety',
 'polyuria',
 'chills',
 'mild_fever',
 'weakness_in_limbs',
 'depression',
 'lethargy',
 'redness_of_eyes',
 'loss_of_balance',
 'blood_in_sputum',
 'throat_irritation',
 'nodal_skin_eruptions',
 'skin_peeling',
 'brittle_nails',
 'bruising',
 'malaise',
 'passage_of_gases',
 'red_sore_around_nose',
 'foul_smell_of urine',
 'weight_loss',
 'swelling_of_stomach',
 'enlarged_thyroid',
 'blister',
 'irritability',
 'acute_liver_failure',
 'congestion',
 'altered_sensorium',
 'slurred_speech',
 'history_of_alcohol_consumption',
 'scurring',
 'yellowing_of_eyes',
 'puffy_face_and_eyes',
 'patches_in_throat',
 'dizziness',
 'swollen_blood_vessels',
 'fatigue',
 'loss_of_smell',
 'vomiting',
 'receiving_blood_transfusion',
 'continuous_feel_of_urine',
 'pus_filled_pimples',
 'chest_pain',
 'silver_like_dusting',
 'pain_in_anal_region',
 'inflammatory_nails',
 'bloody_stool',
 'spinning_movements',
 'swelled_lymph_nodes',
 'cramps',
 'irritation_in_anus',
 'fast_heart_rate',
 'acidity',
 'dehydration',
 'phlegm',
 nan,
 'movement_stiffness',
 'receiving_unsterile_injections',
 'loss_of_appetite',
 'constipation',
 'knee_pain',
 'itching',
 'pain_behind_the_eyes',
 'muscle_weakness',
 'restlessness',
 'swollen_legs',
 'yellow_urine',
 'muscle_wasting',
 'yellowish_skin']

In [12]:
var_mod = ['Disease']
le = LabelEncoder()
for i in var_mod:
    dis_sym_data_v1[i] = le.fit_transform(dis_sym_data_v1[i])

In [20]:
# Save the encoder using pickle
import pickle
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(le, file)

In [32]:
X = dis_sym_data_v1.drop(columns="Disease")
y = dis_sym_data_v1['Disease']

In [33]:
X.shape

(4920, 132)

In [40]:
for i in X.columns:
    print(i)

dischromic _patches
visual_disturbances
yellow_crust_ooze
internal_itching
excessive_hunger
increased_appetite
weight_gain
irregular_sugar_level
mood_swings
hip_joint_pain
unsteadiness
abdominal_pain
palpitations
extra_marital_contacts
high_fever
nausea
family_history
skin_rash
stomach_bleeding
cough
spotting_ urination
mucoid_sputum
red_spots_over_body
breathlessness
stomach_pain
small_dents_in_nails
drying_and_tingling_lips
ulcers_on_tongue
bladder_discomfort
watering_from_eyes
coma
lack_of_concentration
obesity
neck_pain
continuous_sneezing
sunken_eyes
weakness_of_one_body_side
distention_of_abdomen
stiff_neck
burning_micturition
blackheads
swollen_extremeties
diarrhoea
painful_walking
indigestion
sweating
muscle_pain
runny_nose
sinus_pressure
swelling_joints
fluid_overload
pain_during_bowel_movements
belly_pain
toxic_look_(typhos)
prominent_veins_on_calf
shivering
rusty_sputum
abnormal_menstruation
back_pain
blurred_and_distorted_vision
headache
cold_hands_and_feets
dark_urine
joint_pain
anxiety
polyuria
chills
mild_fever
weakness_in_limbs
depression
lethargy
redness_of_eyes
loss_of_balance
blood_in_sputum
throat_irritation
nodal_skin_eruptions
skin_peeling
brittle_nails
bruising
malaise
passage_of_gases
red_sore_around_nose
foul_smell_of urine
weight_loss
swelling_of_stomach
enlarged_thyroid
blister
irritability
acute_liver_failure
congestion
altered_sensorium
slurred_speech
history_of_alcohol_consumption
scurring
yellowing_of_eyes
puffy_face_and_eyes
patches_in_throat
dizziness
swollen_blood_vessels
fatigue
loss_of_smell
vomiting
receiving_blood_transfusion
continuous_feel_of_urine
pus_filled_pimples
chest_pain
silver_like_dusting
pain_in_anal_region
inflammatory_nails
bloody_stool
spinning_movements
swelled_lymph_nodes
cramps
irritation_in_anus
fast_heart_rate
acidity
dehydration
phlegm
nan
movement_stiffness
receiving_unsterile_injections
loss_of_appetite
constipation
knee_pain
itching
pain_behind_the_eyes
muscle_weakness
restlessness
swollen_legs
yellow_urine
muscle_wasting
yellowish_skin

In [41]:
y

0       15
1       15
2       15
3       15
4       15
        ..
4915     0
4916     2
4917    38
4918    35
4919    27
Name: Disease, Length: 4920, dtype: int32

In [36]:
import joblib
def class_algo(model,independent,dependent):
    model.fit(independent,dependent)
    pred = model.predict(independent)
    accuracy = metrics.accuracy_score(pred,dependent) 
    print(model_name,'Accuracy : %s' % '{0:.3%}'.format(accuracy))
    model_filename = f"{model.__class__.__name__}_model.pkl"
    joblib.dump(model, model_filename)  # Save the model to a file
    print(f"Model saved as {model_filename}\n")

In [37]:
algorithms = {'Logistic Regression': 
              {"model": LogisticRegression()},
              
              'Decision Tree': 
              {"model": tree.DecisionTreeClassifier()},
              
              'Random Forest': 
              {"model": RandomForestClassifier()},
              
              'SVM':
              {"model": svm.SVC(probability=True)},
              
              'NaiveBayes' :
              {"model": GaussianNB()},
              
              'K-Nearest Neighbors' :
              {"model": KNeighborsClassifier()},
             }

In [38]:
for model_name, values in algorithms.items():
    class_algo(values["model"],X,y)

TypeError: Feature names are only supported if all input features have string names, but your input has ['float', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
import joblib

# Load the dataset
pd.set_option('display.max_colwidth', None)
dis_sym_data = pd.read_csv(r"Original_Dataset.csv")

# Ensure column names are strings to avoid errors
dis_sym_data.columns = dis_sym_data.columns.astype(str)

# Generate binary features for symptoms
columns_to_check = [col for col in dis_sym_data.columns if col != 'Disease']

# Flatten symptoms, deduplicate, and create binary features
symptoms = dis_sym_data.iloc[:, 1:].values.flatten()
symptoms = list(set(symptoms[~pd.isnull(symptoms)]))  # Remove NaN values

for symptom in symptoms:
    dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
        lambda row: int(symptom in row.values), axis=1
    )

# Drop original symptom columns to keep only binary features
dis_sym_data_v1 = dis_sym_data.drop(columns=columns_to_check)

# Ensure no NaN column names exist
dis_sym_data_v1 = dis_sym_data_v1.loc[:, dis_sym_data_v1.columns.notna()]

# Strip whitespace from column names
dis_sym_data_v1.columns = dis_sym_data_v1.columns.str.strip()

# Encode the target variable
var_mod = ['Disease']
le = LabelEncoder()
for col in var_mod:
    dis_sym_data_v1[col] = le.fit_transform(dis_sym_data_v1[col])

# Split data into features and target
X = dis_sym_data_v1.drop(columns="Disease")
y = dis_sym_data_v1['Disease']

# Define a function to train models and save them
def class_algo(model, independent, dependent, model_name):
    model.fit(independent, dependent)
    pred = model.predict(independent)
    accuracy = metrics.accuracy_score(pred, dependent)
    print(f"{model_name} Accuracy: {accuracy:.3%}")
    model_filename = f"{model.__class__.__name__}_model.pkl"
    joblib.dump(model, model_filename)  # Save the model to a file
    print(f"Model saved as {model_filename}\n")

# Define algorithms
algorithms = {
    'Logistic Regression': {"model": LogisticRegression()},
    'Decision Tree': {"model": tree.DecisionTreeClassifier()},
    'Random Forest': {"model": RandomForestClassifier()},
    'SVM': {"model": svm.SVC(probability=True)},
    'Naive Bayes': {"model": GaussianNB()},
    'K-Nearest Neighbors': {"model": KNeighborsClassifier()},
}

# Train and save models
for model_name, values in algorithms.items():
    class_algo(values["model"], X, y, model_name)

C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\1587393006.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(

Logistic Regression Accuracy: 100.000%
Model saved as LogisticRegression_model.pkl

Decision Tree Accuracy: 100.000%
Model saved as DecisionTreeClassifier_model.pkl

Random Forest Accuracy: 100.000%
Model saved as RandomForestClassifier_model.pkl

SVM Accuracy: 100.000%
Model saved as SVC_model.pkl

Naive Bayes Accuracy: 100.000%
Model saved as GaussianNB_model.pkl

K-Nearest Neighbors Accuracy: 100.000%
Model saved as KNeighborsClassifier_model.pkl

In [21]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
import joblib

# Load the dataset
pd.set_option('display.max_colwidth', None)
dis_sym_data = pd.read_csv(r"Original_Dataset.csv")

# Ensure column names are strings to avoid errors
dis_sym_data.columns = dis_sym_data.columns.astype(str)

# Generate binary features for symptoms
columns_to_check = [col for col in dis_sym_data.columns if col != 'Disease']

# Flatten symptoms, deduplicate, and create binary features
symptoms = dis_sym_data.iloc[:, 1:].values.flatten()
symptoms = list(set(symptoms[~pd.isnull(symptoms)]))  # Remove NaN values

for symptom in symptoms:
    dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
        lambda row: int(symptom in row.values), axis=1
    )

# Drop original symptom columns to keep only binary features
dis_sym_data_v1 = dis_sym_data.drop(columns=columns_to_check)

# Ensure no NaN column names exist
dis_sym_data_v1 = dis_sym_data_v1.loc[:, dis_sym_data_v1.columns.notna()]

# Strip whitespace from column names
dis_sym_data_v1.columns = dis_sym_data_v1.columns.str.strip()

# Encode the target variable
var_mod = ['Disease']
le = LabelEncoder()
for col in var_mod:
    dis_sym_data_v1[col] = le.fit_transform(dis_sym_data_v1[col])

# Save the LabelEncoder for later use
joblib.dump(le, "label_encoder.pkl")
print("LabelEncoder saved as 'label_encoder.pkl'")

# Split data into features and target
X = dis_sym_data_v1.drop(columns="Disease")
y = dis_sym_data_v1['Disease']

# Define a function to train models
def train_and_save_models(models, X, y):
    trained_algorithms = {}

    for model_name, model_info in models.items():
        model = model_info["model"]
        model.fit(X, y)
        pred = model.predict(X)
        accuracy = metrics.accuracy_score(pred, y)
        print(f"{model_name} Accuracy: {accuracy:.3%}")
        trained_algorithms[model_name] = {"model": model, "accuracy": accuracy}

    # Save all trained models to a single file
    joblib.dump(trained_algorithms, "trained_algorithms.pkl")
    print("All trained algorithms saved as 'trained_algorithms.pkl'")

# Define algorithms
algorithms = {
    'Logistic Regression': {"model": LogisticRegression(max_iter=1000)},
    'Decision Tree': {"model": tree.DecisionTreeClassifier()},
    'Random Forest': {"model": RandomForestClassifier()},
    'SVM': {"model": svm.SVC(probability=True)},
    'Naive Bayes': {"model": GaussianNB()},
    'K-Nearest Neighbors': {"model": KNeighborsClassifier()},
}

# Train and save all models
train_and_save_models(algorithms, X, y)

C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
C:\Users\user\AppData\Local\Temp\ipykernel_9932\3133743158.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(

LabelEncoder saved as 'label_encoder.pkl'
Logistic Regression Accuracy: 100.000%
Decision Tree Accuracy: 100.000%
Random Forest Accuracy: 100.000%
SVM Accuracy: 100.000%
Naive Bayes Accuracy: 100.000%
K-Nearest Neighbors Accuracy: 100.000%
All trained algorithms saved as 'trained_algorithms.pkl'

In [2]:
doc_data = pd.read_csv(r"Doctor_Versus_Disease.csv",encoding='latin1', names=['Disease','Specialist'])

In [3]:
doc_data

                                    Disease           Specialist
0                             Drug Reaction            Allergist
1                                   Allergy            Allergist
2                             Hypertension          Cardiologist
3                              Heart attack         Cardiologist
4                                 Psoriasis        Dermatologist
5                               Chicken pox        Dermatologist
6                                      Acne        Dermatologist
7                                  Impetigo        Dermatologist
8                          Fungal infection        Dermatologist
9                            Hypothyroidism      Endocrinologist
10                                Diabetes       Endocrinologist
11                             Hypoglycemia      Endocrinologist
12                          Hyperthyroidism      Endocrinologist
13                                     GERD   Gastroenterologist
14                      Peptic ulcer diseae   Gastroenterologist
15                                 Jaundice   Gastroenterologist
16             Dimorphic hemmorhoids(piles)  Gastroenterologist
17                          Gastroenteritis   Gastroenterologist
18                  Urinary tract infection         Gynecologist
19                      Chronic cholestasis         Hepatologist
20                              hepatitis A         Hepatologist
21                              Hepatitis B         hepatologist
22                              Hepatitis C         Hepatologist
23                              Hepatitis E         Hepatologist
24                              Hepatitis D         Hepatologist
25                      Alcoholic hepatitis         Hepatologist
26                                  Malaria     Internal Medcine
27                                   Dengue     Internal Medcine
28                                 Migraine          Neurologist
29                     Cervical spondylosis          Neurologist
30             Paralysis (brain hemorrhage)          Neurologist
31                                     AIDS          Osteopathic
32  (vertigo) Paroymsal  Positional Vertigo     Otolaryngologist
33                              Common Cold     Otolaryngologist
34                                  Typhoid         Pediatrician
35                           Varicose veins         Phlebologist
36                         Bronchial Asthma        Pulmonologist
37                                Pneumonia        Pulmonologist
38                          Osteoarthristis      Rheumatologists
39                                Arthritis      Rheumatologists
40                             Tuberculosis         Tuberculosis

In [4]:
doc_data1= pd.read_csv(r"Doctor_Versus_Disease.csv",encoding='latin1', names=['Disease'])

In [5]:
doc_data1

                                                     Disease
Drug Reaction                                      Allergist
Allergy                                            Allergist
Hypertension                                    Cardiologist
Heart attack                                    Cardiologist
Psoriasis                                      Dermatologist
Chicken pox                                    Dermatologist
Acne                                           Dermatologist
Impetigo                                       Dermatologist
Fungal infection                               Dermatologist
Hypothyroidism                               Endocrinologist
Diabetes                                     Endocrinologist
Hypoglycemia                                 Endocrinologist
Hyperthyroidism                              Endocrinologist
GERD                                      Gastroenterologist
Peptic ulcer diseae                       Gastroenterologist
Jaundice                                  Gastroenterologist
Dimorphic hemmorhoids(piles)             Gastroenterologist
Gastroenteritis                           Gastroenterologist
Urinary tract infection                         Gynecologist
Chronic cholestasis                             Hepatologist
hepatitis A                                     Hepatologist
Hepatitis B                                     hepatologist
Hepatitis C                                     Hepatologist
Hepatitis E                                     Hepatologist
Hepatitis D                                     Hepatologist
Alcoholic hepatitis                             Hepatologist
Malaria                                     Internal Medcine
Dengue                                      Internal Medcine
Migraine                                         Neurologist
Cervical spondylosis                             Neurologist
Paralysis (brain hemorrhage)                     Neurologist
AIDS                                             Osteopathic
(vertigo) Paroymsal  Positional Vertigo     Otolaryngologist
Common Cold                                 Otolaryngologist
Typhoid                                         Pediatrician
Varicose veins                                  Phlebologist
Bronchial Asthma                               Pulmonologist
Pneumonia                                      Pulmonologist
Osteoarthristis                              Rheumatologists
Arthritis                                    Rheumatologists
Tuberculosis                                    Tuberculosis

In [7]:
import numpy as np
doc_data['Specialist'] = np.where((doc_data['Disease'] == 'Tuberculosis'),'Pulmonologist', doc_data['Specialist'])

In [2]:
des_data = pd.read_csv(r"Disease_Description.csv")

In [3]:
des_data

,Disease,Description
0,Drug Reaction,An adverse drug reaction (ADR) is an injury ca...
1,Malaria,An infectious disease caused by protozoan para...
2,Allergy,An allergy is an immune system response to a f...
3,Hypothyroidism,"Hypothyroidism, also called underactive thyroi..."
4,Psoriasis,Psoriasis is a common skin disorder that forms...
5,GERD,"Gastroesophageal reflux disease, or GERD, is a..."
6,Chronic cholestasis,"Chronic cholestatic diseases, whether occurrin..."
7,hepatitis A,Hepatitis A is a highly contagious liver infec...
8,Osteoarthristis,Osteoarthritis is the most common form of arth...
9,(vertigo) Paroymsal Positional Vertigo,Benign paroxysmal positional vertigo (BPPV) is...
10,Hypoglycemia,Hypoglycemia is a condition in which your blo...
11,Acne,"Acne vulgaris is the formation of comedones, p..."
12,Diabetes,Diabetes is a disease that occurs when your bl...
13,Impetigo,Impetigo (im-puh-TIE-go) is a common and highl...
14,Hypertension,"Hypertension (HTN or HT), also known as high b..."
15,Peptic ulcer diseae,Peptic ulcer disease (PUD) is a break in the i...
16,Dimorphic hemorrhoids(piles),"Hemorrhoids, also spelled haemorrhoids, are va..."
17,Common Cold,The common cold is a viral infection of your n...
18,Chicken pox,Chickenpox is a highly contagious disease caus...
19,Cervical spondylosis,Cervical spondylosis is a general term for age...
20,Hyperthyroidism,Hyperthyroidism (overactive thyroid) occurs wh...
21,Urinary tract infection,Urinary tract infection: An infection of the k...
22,Varicose veins,"A vein that has enlarged and twisted, often ap..."
23,AIDS,Acquired immunodeficiency syndrome (AIDS) is a...
24,Paralysis (brain hemorrhage),Intracerebral hemorrhage (ICH) is when blood s...
25,Typhoid,An acute illness characterized by fever caused...
26,Hepatitis B,Hepatitis B is an infection of your liver. It ...
27,Fungal infection,"In humans, fungal infections occur when an inv..."
28,Hepatitis C,Inflammation of the liver due to the hepatitis...
29,Migraine,A migraine can cause severe throbbing pain or ...
30,Bronchial Asthma,Bronchial asthma is a medical condition which ...
31,Alcoholic hepatitis,"Alcoholic hepatitis is a diseased, inflammator..."
32,Jaundice,Yellow staining of the skin and sclerae (the w...
33,Hepatitis E,A rare form of liver inflammation caused by in...
34,Dengue,an acute infectious disease caused by a flaviv...
35,Hepatitis D,"Hepatitis D, also known as the hepatitis delta..."
36,Heart attack,The death of heart muscle due to the loss of b...
37,Pneumonia,Pneumonia is an infection in one or both lungs...
38,Arthritis,Arthritis is the swelling and tenderness of on...
39,Gastroenteritis,Gastroenteritis is an inflammation of the dige...
40,Tuberculosis,Tuberculosis (TB) is an infectious disease usu...

In [4]:
des_data["Disease"]

0                               Drug Reaction
1                                     Malaria
2                                     Allergy
3                              Hypothyroidism
4                                   Psoriasis
5                                        GERD
6                         Chronic cholestasis
7                                 hepatitis A
8                             Osteoarthristis
9     (vertigo) Paroymsal  Positional Vertigo
10                               Hypoglycemia
11                                       Acne
12                                   Diabetes
13                                   Impetigo
14                               Hypertension
15                        Peptic ulcer diseae
16               Dimorphic hemorrhoids(piles)
17                                Common Cold
18                                Chicken pox
19                       Cervical spondylosis
20                            Hyperthyroidism
21                    Urinary tract infection
22                             Varicose veins
23                                       AIDS
24               Paralysis (brain hemorrhage)
25                                    Typhoid
26                                Hepatitis B
27                           Fungal infection
28                                Hepatitis C
29                                   Migraine
30                           Bronchial Asthma
31                        Alcoholic hepatitis
32                                   Jaundice
33                                Hepatitis E
34                                     Dengue
35                                Hepatitis D
36                               Heart attack
37                                  Pneumonia
38                                  Arthritis
39                            Gastroenteritis
40                               Tuberculosis
Name: Disease, dtype: object

In [12]:
from collections import Counter
test_col = []
for col in dis_sym_data_v1.columns:
    if col != 'Disease':
        test_col.append(col)


test_data = {}
symptoms = []
predicted = []
def test_input():
    symptoms.clear()
    predicted.clear()
    num_inputs = int(input("Enter the number of symptoms you have: "))
    for i in range(num_inputs):
        user_input = input("Enter Symptoms #{}: ".format(i+1))
        symptoms.append(user_input)
    print("Symptoms you have:", symptoms)
    for column in test_col:
        test_data[column] = 1 if column in symptoms else 0
        test_df = pd.DataFrame(test_data, index=[0])
    print("Predicting Disease based on 6 ML algorithms...")
    for model_name, values in algorithms.items():
        predict_disease = values["model"].predict(test_df)
        predict_disease = le.inverse_transform(predict_disease)
        predicted.extend(predict_disease)
    disease_counts = Counter(predicted)
    percentage_per_disease = {disease: (count / 6) * 100 for disease, count in disease_counts.items()}
    result_df = pd.DataFrame({"Disease": list(percentage_per_disease.keys()),
                               "Chances": list(percentage_per_disease.values())})
    result_df = result_df.merge(doc_data, on='Disease', how='left')
    result_df = result_df.merge(des_data, on='Disease', how='left')
    return result_df

In [15]:
test_input()

KeyboardInterrupt: Interrupted by user

In [34]:
pip install gradio

Requirement already satisfied: gradio in c:\users\t470p\anaconda3\lib\site-packages (5.8.0)
Requirement already satisfied: aiofiles<24.0,>=22.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (23.2.1)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (4.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.115.6)
Requirement already satisfied: ffmpy in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.4.0)
Requirement already satisfied: gradio-client==1.5.1 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (1.5.1)
Requirement already satisfied: httpx>=0.24.1 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.27.0)
Requirement already satisfied: huggingface-hub>=0.25.1 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.26.3)
Requirement already satisfied: jinja2<4.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (3.1.4)
Requirement already satisfied: markupsafe~=2.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (2.1.3)
Requirement already satisfied: numpy<3.0,>=1.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (1.26.4)
Requirement already satisfied: orjson~=3.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (3.10.12)
Requirement already satisfied: packaging in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (24.1)
Requirement already satisfied: pandas<3.0,>=1.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (10.4.0)
Requirement already satisfied: pydantic>=2.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (2.8.2)
Requirement already satisfied: pydub in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.0.19)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (6.0.1)
Requirement already satisfied: ruff>=0.2.2 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.8.2)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.1.6)
Requirement already satisfied: semantic-version~=2.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.41.3)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.13.2)
Requirement already satisfied: typer<1.0,>=0.12 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.15.1)
Requirement already satisfied: typing-extensions~=4.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (4.11.0)
Requirement already satisfied: uvicorn>=0.14.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio) (0.32.1)
Requirement already satisfied: fsspec in c:\users\t470p\anaconda3\lib\site-packages (from gradio-client==1.5.1->gradio) (2024.6.1)
Requirement already satisfied: websockets<15.0,>=10.0 in c:\users\t470p\anaconda3\lib\site-packages (from gradio-client==1.5.1->gradio) (14.1)
Requirement already satisfied: idna>=2.8 in c:\users\t470p\anaconda3\lib\site-packages (from anyio<5.0,>=3.0->gradio) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\t470p\anaconda3\lib\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.0)
Requirement already satisfied: certifi in c:\users\t470p\anaconda3\lib\site-packages (from httpx>=0.24.1->gradio) (2024.8.30)
Requirement already satisfied: httpcore==1.* in c:\users\t470p\anaconda3\lib\site-packages (from httpx>=0.24.1->gradio) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\t470p\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in c:\users\t470p\anaconda3\lib\site-packages (from huggingface-hub>=0.25.1->gradio) (3.13.1)
Requirement already satisfied: requests in c:\users\t470p\anaconda3\lib\site-packages (from huggingface-hub>=0.25.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\t470p\anaconda3\lib\site-packages (from huggingface-hub>=0.25.1->gradio) (4.66.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\t470p\anaconda3\lib\site-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\t470p\anaconda3\lib\site-packages (from pandas<3.0,>=1.0->gradio) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\t470p\anaconda3\lib\site-packages (from pandas<3.0,>=1.0->gradio) (2023.3)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\t470p\anaconda3\lib\site-packages (from pydantic>=2.0->gradio) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\t470p\anaconda3\lib\site-packages (from pydantic>=2.0->gradio) (2.20.1)
Requirement already satisfied: click>=8.0.0 in c:\users\t470p\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\t470p\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\t470p\anaconda3\lib\site-packages (from typer<1.0,>=0.12->gradio) (13.7.1)
Requirement already satisfied: colorama in c:\users\t470p\anaconda3\lib\site-packages (from click>=8.0.0->typer<1.0,>=0.12->gradio) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\t470p\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\t470p\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\t470p\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.15.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\t470p\anaconda3\lib\site-packages (from requests->huggingface-hub>=0.25.1->gradio) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\t470p\anaconda3\lib\site-packages (from requests->huggingface-hub>=0.25.1->gradio) (2.2.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\t470p\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [14]:
import gradio as gr
import pandas as pd
from collections import Counter

# Assume `dis_sym_data_v1`, `doc_data`, `des_data`, `algorithms`, and `le` are preloaded or defined elsewhere

# Column names excluding 'Disease'
test_col = [col for col in dis_sym_data_v1.columns if col != 'Disease']

# Store chatbot state globally
symptoms = []
num_symptoms = 0
current_step = 0

def reset_state():
    global symptoms, num_symptoms, current_step
    symptoms = []
    num_symptoms = 0
    current_step = 0

# Function to predict disease once all symptoms are gathered
def predict_disease_chatbot():
    test_data = {}
    predicted = []

    # Prepare test data for prediction
    for column in test_col:
        test_data[column] = 1 if column in symptoms else 0
    test_df = pd.DataFrame(test_data, index=[0])

    # Predict using multiple algorithms and collect predictions
    for model_name, values in algorithms.items():
        predict_disease = values["model"].predict(test_df)
        predict_disease = le.inverse_transform(predict_disease)
        predicted.extend(predict_disease)

    # Calculate the chances of each predicted disease
    disease_counts = Counter(predicted)
    percentage_per_disease = {disease: (count / 6) * 100 for disease, count in disease_counts.items()}

    # Convert to DataFrame
    result_df = pd.DataFrame({"Disease": list(percentage_per_disease.keys()),
                              "Chances": list(percentage_per_disease.values())})

    # Merge additional information (doctor and description)
    result_df = result_df.merge(doc_data, on='Disease', how='left')
    result_df = result_df.merge(des_data, on='Disease', how='left')

    # Format the response
    response = "Here are the predictions based on your symptoms:\n"
    for index, row in result_df.iterrows():
        doctor_info = row.get('Doctor', 'Doctor info not available')
        description_info = row.get('Description', 'Description not available')
        response += f"Disease: {row['Disease']}\nChances: {row['Chances']:.2f}%\nDoctor: {doctor_info}\nDescription: {description_info}\n\n"
    
    reset_state()  # Reset state after prediction
    return response

# Function to handle user inputs step by step, while maintaining the chat history
def chatbot_interface(user_input, chat_history=[]):
    global symptoms, num_symptoms, current_step

    if current_step == 0:
        # Step 1: Ask how many symptoms the user has
        try:
            num_symptoms = int(user_input)
            current_step = 1
            response = f"Okay, you have {num_symptoms} symptoms. Please enter symptom #1."
        except ValueError:
            response = "Please enter a valid number of symptoms."

    elif current_step <= num_symptoms:
        # Step 2: Collect symptoms one by one
        symptoms.append(user_input)
        if current_step < num_symptoms:
            current_step += 1
            response = f"Please enter symptom #{current_step}."
        else:
            # Step 3: Make the prediction
            response = predict_disease_chatbot()

    # Append the user input and chatbot response to the chat history
    chat_history.append((f"User: {user_input}", f"Chatbot: {response}"))
    
    return chat_history, chat_history  # Return the updated chat history and state

# Gradio chatbot interface with a submit button
iface = gr.Interface(
    fn=chatbot_interface,
    inputs=[gr.Textbox(label="Enter your message", placeholder="Please Enter How many symptoms you have....", lines=1), gr.State([])],  # Textbox input and chat history state
    outputs=[gr.Chatbot(), gr.State([])],  # Output chatbot conversation and chat history state
    title="Disease Prediction Chatbot",
    description="Chatbot to predict possible diseases based on symptoms. First, enter the number of symptoms, and then enter each symptom one by one.",
    allow_flagging="never"
)

# Launch the chatbot interface
iface.launch()

C:\Users\user\anaconda3\Lib\site-packages\gradio\components\chatbot.py:242: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style dictionaries with 'role' and 'content' keys.
  warnings.warn(
C:\Users\user\anaconda3\Lib\site-packages\gradio\interface.py:399: UserWarning: The `allow_flagging` parameter in `Interface` is deprecated.Use `flagging_mode` instead.
  warnings.warn(

* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

In [74]:
import gradio as gr
import pandas as pd
from collections import Counter
import joblib  # Import joblib for loading the saved models

# Assume the following files for the models:
model_files = {
    'Logistic Regression': 'LogisticRegression_model.pkl',
    'Decision Tree': 'DecisionTreeClassifier_model.pkl',
    'Random Forest': 'RandomForestClassifier_model.pkl',
    'SVM': 'SVC_model.pkl',
    'NaiveBayes': 'GaussianNB_model.pkl',
    'K-Nearest Neighbors': 'KNeighborsClassifier_model.pkl'
}

# Load the models from .pkl files
algorithms = {}
for model_name, model_file in model_files.items():
    algorithms[model_name] = {"model": joblib.load(model_file)}

# Assuming `dis_sym_data_v1`, `doc_data`, `des_data`, and `le` are preloaded or defined elsewhere

# Column names excluding 'Disease'
test_col = [col for col in dis_sym_data_v1.columns if col != 'Disease']

# Store chatbot state globally
symptoms = []
num_symptoms = 0
current_step = 0

def reset_state():
    global symptoms, num_symptoms, current_step
    symptoms = []
    num_symptoms = 0
    current_step = 0

# Function to predict disease once all symptoms are gathered
def predict_disease_chatbot():
    test_data = {}
    predicted = []

    # Prepare test data for prediction
    for column in test_col:
        test_data[column] = 1 if column in symptoms else 0
    test_df = pd.DataFrame(test_data, index=[0])
    print(test_df)
    # Predict using multiple algorithms and collect predictions
    for model_name, values in algorithms.items():
        predict_disease = values["model"].predict(test_df)
        predict_disease = le.inverse_transform(predict_disease)
        predicted.extend(predict_disease)
    
    # Calculate the chances of each predicted disease
    disease_counts = Counter(predicted)
    percentage_per_disease = {disease: (count / 6) * 100 for disease, count in disease_counts.items()}

    # Convert to DataFrame
    result_df = pd.DataFrame({"Disease": list(percentage_per_disease.keys()),
                              "Chances": list(percentage_per_disease.values())})

    # Merge additional information (doctor and description)
    result_df = result_df.merge(doc_data, on='Disease', how='left')
    result_df = result_df.merge(des_data, on='Disease', how='left')

    # Format the response
    response = "Here are the predictions based on your symptoms:\n"
    for index, row in result_df.iterrows():
        doctor_info = row.get('Doctor', 'Doctor info not available')
        description_info = row.get('Description', 'Description not available')
        response += f"Disease: {row['Disease']}\nChances: {row['Chances']:.2f}%\nDoctor: {doctor_info}\nDescription: {description_info}\n\n"
    
    reset_state()  # Reset state after prediction
    return response

# Function to handle user inputs step by step, while maintaining the chat history
def chatbot_interface(user_input, chat_history=[]):
    global symptoms, num_symptoms, current_step

    if current_step == 0:
        # Step 1: Ask how many symptoms the user has
        try:
            num_symptoms = int(user_input)
            current_step = 1
            response = f"Okay, you have {num_symptoms} symptoms. Please enter symptom #1."
        except ValueError:
            response = "Please enter a valid number of symptoms."

    elif current_step <= num_symptoms:
        # Step 2: Collect symptoms one by one
        symptoms.append(user_input)
        if current_step < num_symptoms:
            current_step += 1
            response = f"Please enter symptom #{current_step}."
        else:
            # Step 3: Make the prediction
            response = predict_disease_chatbot()

    # Append the user input and chatbot response to the chat history
    chat_history.append((f"User: {user_input}", f"Chatbot: {response}"))
    
    return chat_history, chat_history  # Return the updated chat history and state

# Gradio chatbot interface with a submit button
iface = gr.Interface(
    fn=chatbot_interface,
    inputs=[gr.Textbox(label="Enter your message", placeholder="Please Enter How many symptoms you have....", lines=1), gr.State([])],  # Textbox input and chat history state
    outputs=[gr.Chatbot(), gr.State([])],  # Output chatbot conversation and chat history state
    title="Disease Prediction Chatbot",
    description="Chatbot to predict possible diseases based on symptoms. First, enter the number of symptoms, and then enter each symptom one by one.",
    allow_flagging="never"
)

# Launch the chatbot interface
iface.launch()

* Running on local URL:  http://127.0.0.1:7863

To create a public link, set `share=True` in `launch()`.

In [16]:
import gradio as gr
import pandas as pd
from collections import Counter

# Assume `dis_sym_data_v1`, `doc_data`, `des_data`, `algorithms`, and `le` are preloaded or defined elsewhere

# Column names excluding 'Disease'
test_col = [col for col in dis_sym_data_v1.columns if col != 'Disease']

# Store chatbot state globally
symptoms = []
num_symptoms = 0
current_step = 0

def reset_state():
    global symptoms, num_symptoms, current_step
    symptoms = []
    num_symptoms = 0
    current_step = 0

# Function to predict disease once all symptoms are gathered
def predict_disease_chatbot():
    test_data = {}
    predicted = []

    # Prepare test data for prediction
    for column in test_col:
        test_data[column] = 1 if column in symptoms else 0
    test_df = pd.DataFrame(test_data, index=[0])

    # Predict using multiple algorithms and collect predictions
    for model_name, values in algorithms.items():
        predict_disease = values["model"].predict(test_df)
        predict_disease = le.inverse_transform(predict_disease)
        predicted.extend(predict_disease)

    # Calculate the chances of each predicted disease
    disease_counts = Counter(predicted)
    percentage_per_disease = {disease: (count / len(algorithms)) * 100 for disease, count in disease_counts.items()}

    # Convert to DataFrame
    result_df = pd.DataFrame({"Disease": list(percentage_per_disease.keys()),
                              "Chances": list(percentage_per_disease.values())})

    # Merge additional information (specialist and description)
    result_df = result_df.merge(doc_data, on='Disease', how='left')
    result_df = result_df.merge(des_data, on='Disease', how='left')

    # Format the response
    response = "Here are the predictions based on your symptoms:\n"
    for index, row in result_df.iterrows():
        specialist_info = row.get('Specialist', 'Specialist info not available')
        description_info = row.get('Description', 'Description not available')
        response += f"Disease: {row['Disease']}\nChances: {row['Chances']:.2f}%\nSpecialist: {specialist_info}\nDescription: {description_info}\n\n"

    reset_state()  # Reset state after prediction
    return response

# Function to handle user inputs step by step, while maintaining the chat history
def chatbot_interface(user_input, chat_history=[]):
    global symptoms, num_symptoms, current_step

    if current_step == 0:
        # Step 1: Ask how many symptoms the user has
        try:
            num_symptoms = int(user_input)
            current_step = 1
            response = f"Okay, you have {num_symptoms} symptoms. Please enter symptom #1."
        except ValueError:
            response = "Please enter a valid number of symptoms."

    elif current_step <= num_symptoms:
        # Step 2: Collect symptoms one by one
        symptoms.append(user_input)
        if current_step < num_symptoms:
            current_step += 1
            response = f"Please enter symptom #{current_step}."
        else:
            # Step 3: Make the prediction
            response = predict_disease_chatbot()

    # Append the user input and chatbot response to the chat history
    chat_history.append((f"User: {user_input}", f"Chatbot: {response}"))
    
    return chat_history, chat_history  # Return the updated chat history and state

# Gradio chatbot interface with a submit button
iface = gr.Interface(
    fn=chatbot_interface,
    inputs=[gr.Textbox(label="Enter your message", placeholder="Please Enter How many symptoms you have....", lines=1), gr.State([])],  # Textbox input and chat history state
    outputs=[gr.Chatbot(), gr.State([])],  # Output chatbot conversation and chat history state
    title="Disease Prediction Chatbot",
    description="Chatbot to predict possible diseases based on symptoms. First, enter the number of symptoms, and then enter each symptom one by one.",
    allow_flagging="never"
)

# Launch the chatbot interface
iface.launch()

C:\Users\user\anaconda3\Lib\site-packages\gradio\components\chatbot.py:242: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style dictionaries with 'role' and 'content' keys.
  warnings.warn(
C:\Users\user\anaconda3\Lib\site-packages\gradio\interface.py:399: UserWarning: The `allow_flagging` parameter in `Interface` is deprecated.Use `flagging_mode` instead.
  warnings.warn(

* Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.