##### !pip install pandas

In [1]:
!pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [2]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from seaborn) (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [3]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from scikit-learn) (3.6.0)

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import RandomizedSearchCV
from collections import Counter

In [5]:
import pandas as pd

pd.set_option('display.max_colwidth', None)

In [6]:
dis_sym_data = pd.read_csv(r"Original_Dataset.csv")

In [7]:
dis_sym_data

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4532,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4533,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4534,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4535,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4536,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
columns_to_check = []
for col in dis_sym_data.columns:
    if col != 'Disease':
        columns_to_check.append(col)

In [9]:
symptoms = dis_sym_data.iloc[:, 1:].values.flatten()
symptoms = list(set(symptoms))

In [10]:
for symptom in symptoms:
    dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(lambda row: int(symptom in row.values), axis=1)

dis_sym_data_v1 = dis_sym_data.drop(columns=columns_to_check)

In [11]:
dis_sym_data_v1 = dis_sym_data_v1.loc[:, dis_sym_data_v1.columns.notna()]

In [12]:
dis_sym_data_v1.shape

(4537, 133)

In [13]:
dis_sym_data_v1.columns = dis_sym_data_v1.columns.str.strip()

In [14]:
dis_sym_data_v1.columns

Index(['Disease', 'dark_urine', 'weight_loss', 'blackheads', 'coma',
       'yellowing_of_eyes', 'movement_stiffness', 'rusty_sputum',
       'swollen_extremeties', 'swelled_lymph_nodes',
       ...
       'weakness_in_limbs', 'dehydration', 'excessive_hunger', 'blister',
       'bruising', 'small_dents_in_nails', 'polyuria', 'back_pain',
       'congestion', 'constipation'],
      dtype='object', length=133)

In [15]:
dis_sym_data_v1

,Disease,dark_urine,weight_loss,blackheads,coma,yellowing_of_eyes,movement_stiffness,rusty_sputum,swollen_extremeties,swelled_lymph_nodes,...,weakness_in_limbs,dehydration,excessive_hunger,blister,bruising,small_dents_in_nails,polyuria,back_pain,congestion,constipation
0,Fungal infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Fungal infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Fungal infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Fungal infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Fungal infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4532,(vertigo) Paroymsal Positional Vertigo,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4533,Acne,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4534,Urinary tract infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4535,Psoriasis,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4536,Impetigo,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [16]:
# Select columns that start with "i"
columns_starting_with_i = [col for col in dis_sym_data_v1.columns if col.startswith('itching')]

# Display the rows with only these columns
print(dis_sym_data_v1[columns_starting_with_i])

      itching
0           1
1           1
2           0
3           1
4           1
...       ...
4532        0
4533        0
4534        0
4535        0
4536        0

[4537 rows x 1 columns]

In [17]:
dis_sym_data_v1[columns_starting_with_i]

      itching
0           1
1           1
2           0
3           1
4           1
...       ...
4532        0
4533        0
4534        0
4535        0
4536        0

[4537 rows x 1 columns]

In [18]:
dis_sym_data_v1

,Disease,dark_urine,weight_loss,blackheads,coma,yellowing_of_eyes,movement_stiffness,rusty_sputum,swollen_extremeties,swelled_lymph_nodes,...,weakness_in_limbs,dehydration,excessive_hunger,blister,bruising,small_dents_in_nails,polyuria,back_pain,congestion,constipation
0,Fungal infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Fungal infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Fungal infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Fungal infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Fungal infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4532,(vertigo) Paroymsal Positional Vertigo,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4533,Acne,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4534,Urinary tract infection,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4535,Psoriasis,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4536,Impetigo,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [19]:
dis_sym_data_v1.to_csv("Processed_Dataset1.csv")

In [20]:
symptom = list(dis_sym_data_v1)
symptom

['Disease',
 'dark_urine',
 'weight_loss',
 'blackheads',
 'coma',
 'yellowing_of_eyes',
 'movement_stiffness',
 'rusty_sputum',
 'swollen_extremeties',
 'swelled_lymph_nodes',
 'swelling_of_stomach',
 'phlegm',
 'mild_fever',
 'sunken_eyes',
 'nausea',
 'watering_from_eyes',
 'stomach_pain',
 'pain_in_anal_region',
 'abnormal_menstruation',
 'mucoid_sputum',
 'swollen_legs',
 'brittle_nails',
 'silver_like_dusting',
 'enlarged_thyroid',
 'depression',
 'inflammatory_nails',
 'distention_of_abdomen',
 'bladder_discomfort',
 'receiving_blood_transfusion',
 'puffy_face_and_eyes',
 'visual_disturbances',
 'abdominal_pain',
 'headache',
 'pain_behind_the_eyes',
 'acute_liver_failure',
 'weakness_of_one_body_side',
 'cough',
 'unsteadiness',
 'skin_peeling',
 'fluid_overload',
 'fatigue',
 'lethargy',
 'diarrhoea',
 'irregular_sugar_level',
 'continuous_feel_of_urine',
 'cramps',
 'yellow_urine',
 'sinus_pressure',
 'vomiting',
 'scurring',
 'anxiety',
 'increased_appetite',
 'mood_swings',
 'family_history',
 'extra_marital_contacts',
 'foul_smell_of urine',
 'stiff_neck',
 'slurred_speech',
 'red_sore_around_nose',
 'loss_of_smell',
 'breathlessness',
 'drying_and_tingling_lips',
 'muscle_weakness',
 'loss_of_balance',
 'palpitations',
 'high_fever',
 'restlessness',
 'muscle_pain',
 'skin_rash',
 'swelling_joints',
 'irritability',
 'itching',
 'runny_nose',
 'lack_of_concentration',
 'spotting_ urination',
 'indigestion',
 'belly_pain',
 'fever',
 'joint_pain',
 'blurred_and_distorted_vision',
 'weight_gain',
 'yellow_crust_ooze',
 'stomach_bleeding',
 'acidity',
 'bloody_stool',
 'knee_pain',
 'neck_pain',
 'throat_irritation',
 'chills',
 'spinning_movements',
 'passage_of_gases',
 'sweating',
 'dischromic _patches',
 'hip_joint_pain',
 'burning_micturition',
 'blood_in_sputum',
 'toxic_look_(typhos)',
 'ulcers_on_tongue',
 'receiving_unsterile_injections',
 'cold_hands_and_feets',
 'irritation_in_anus',
 'redness_of_eyes',
 'continuous_sneezing',
 'internal_itching',
 'prominent_veins_on_calf',
 'yellowish_skin',
 'nodal_skin_eruptions',
 'shivering',
 'obesity',
 'chest_pain',
 'pus_filled_pimples',
 'altered_sensorium',
 'dizziness',
 'swollen_blood_vessels',
 'loss_of_appetite',
 'patches_in_throat',
 'history_of_alcohol_consumption',
 'pain_during_bowel_movements',
 'malaise',
 'muscle_wasting',
 'painful_walking',
 'red_spots_over_body',
 'fast_heart_rate',
 'weakness_in_limbs',
 'dehydration',
 'excessive_hunger',
 'blister',
 'bruising',
 'small_dents_in_nails',
 'polyuria',
 'back_pain',
 'congestion',
 'constipation']

In [21]:
var_mod = ['Disease']
le = LabelEncoder()
for i in var_mod:
    dis_sym_data_v1[i] = le.fit_transform(dis_sym_data_v1[i])

In [22]:
# Save the encoder using pickle
import pickle
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(le, file)

In [23]:
X = dis_sym_data_v1.drop(columns="Disease")
y = dis_sym_data_v1['Disease']

In [24]:
X.shape

(4537, 132)

In [25]:
for i in X.columns:
    print(i)

dark_urine
weight_loss
blackheads
coma
yellowing_of_eyes
movement_stiffness
rusty_sputum
swollen_extremeties
swelled_lymph_nodes
swelling_of_stomach
phlegm
mild_fever
sunken_eyes
nausea
watering_from_eyes
stomach_pain
pain_in_anal_region
abnormal_menstruation
mucoid_sputum
swollen_legs
brittle_nails
silver_like_dusting
enlarged_thyroid
depression
inflammatory_nails
distention_of_abdomen
bladder_discomfort
receiving_blood_transfusion
puffy_face_and_eyes
visual_disturbances
abdominal_pain
headache
pain_behind_the_eyes
acute_liver_failure
weakness_of_one_body_side
cough
unsteadiness
skin_peeling
fluid_overload
fatigue
lethargy
diarrhoea
irregular_sugar_level
continuous_feel_of_urine
cramps
yellow_urine
sinus_pressure
vomiting
scurring
anxiety
increased_appetite
mood_swings
family_history
extra_marital_contacts
foul_smell_of urine
stiff_neck
slurred_speech
red_sore_around_nose
loss_of_smell
breathlessness
drying_and_tingling_lips
muscle_weakness
loss_of_balance
palpitations
high_fever
restlessness
muscle_pain
skin_rash
swelling_joints
irritability
itching
runny_nose
lack_of_concentration
spotting_ urination
indigestion
belly_pain
fever
joint_pain
blurred_and_distorted_vision
weight_gain
yellow_crust_ooze
stomach_bleeding
acidity
bloody_stool
knee_pain
neck_pain
throat_irritation
chills
spinning_movements
passage_of_gases
sweating
dischromic _patches
hip_joint_pain
burning_micturition
blood_in_sputum
toxic_look_(typhos)
ulcers_on_tongue
receiving_unsterile_injections
cold_hands_and_feets
irritation_in_anus
redness_of_eyes
continuous_sneezing
internal_itching
prominent_veins_on_calf
yellowish_skin
nodal_skin_eruptions
shivering
obesity
chest_pain
pus_filled_pimples
altered_sensorium
dizziness
swollen_blood_vessels
loss_of_appetite
patches_in_throat
history_of_alcohol_consumption
pain_during_bowel_movements
malaise
muscle_wasting
painful_walking
red_spots_over_body
fast_heart_rate
weakness_in_limbs
dehydration
excessive_hunger
blister
bruising
small_dents_in_nails
polyuria
back_pain
congestion
constipation

In [26]:
y

0       15
1       15
2       15
3       15
4       15
        ..
4532     0
4533     2
4534    38
4535    35
4536    27
Name: Disease, Length: 4537, dtype: int64

In [27]:
import joblib
def class_algo(model,independent,dependent):
    model.fit(independent,dependent)
    pred = model.predict(independent)
    accuracy = metrics.accuracy_score(pred,dependent) 
    print(model_name,'Accuracy : %s' % '{0:.3%}'.format(accuracy))
    model_filename = f"{model.__class__.__name__}_model.pkl"
    joblib.dump(model, model_filename)  # Save the model to a file
    print(f"Model saved as {model_filename}\n")

In [28]:
algorithms = {'Logistic Regression': 
              {"model": LogisticRegression()},
              
              'Decision Tree': 
              {"model": tree.DecisionTreeClassifier()},
              
              'Random Forest': 
              {"model": RandomForestClassifier()},
              
              'SVM':
              {"model": svm.SVC(probability=True)},
              
              'NaiveBayes' :
              {"model": GaussianNB()},
              
              'K-Nearest Neighbors' :
              {"model": KNeighborsClassifier()},
             }

In [29]:
for model_name, values in algorithms.items():
    class_algo(values["model"],X,y)

Logistic Regression Accuracy : 99.978%
Model saved as LogisticRegression_model.pkl

Decision Tree Accuracy : 99.978%
Model saved as DecisionTreeClassifier_model.pkl

Random Forest Accuracy : 99.978%
Model saved as RandomForestClassifier_model.pkl

SVM Accuracy : 99.868%
Model saved as SVC_model.pkl

NaiveBayes Accuracy : 99.956%
Model saved as GaussianNB_model.pkl

K-Nearest Neighbors Accuracy : 99.912%
Model saved as KNeighborsClassifier_model.pkl

In [30]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
import joblib

# Load the dataset
pd.set_option('display.max_colwidth', None)
dis_sym_data = pd.read_csv(r"Original_Dataset.csv")

# Ensure column names are strings to avoid errors
dis_sym_data.columns = dis_sym_data.columns.astype(str)

# Generate binary features for symptoms
columns_to_check = [col for col in dis_sym_data.columns if col != 'Disease']

# Flatten symptoms, deduplicate, and create binary features
symptoms = dis_sym_data.iloc[:, 1:].values.flatten()
symptoms = list(set(symptoms[~pd.isnull(symptoms)]))  # Remove NaN values

for symptom in symptoms:
    dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
        lambda row: int(symptom in row.values), axis=1
    )

# Drop original symptom columns to keep only binary features
dis_sym_data_v1 = dis_sym_data.drop(columns=columns_to_check)

# Ensure no NaN column names exist
dis_sym_data_v1 = dis_sym_data_v1.loc[:, dis_sym_data_v1.columns.notna()]

# Strip whitespace from column names
dis_sym_data_v1.columns = dis_sym_data_v1.columns.str.strip()

# Encode the target variable
var_mod = ['Disease']
le = LabelEncoder()
for col in var_mod:
    dis_sym_data_v1[col] = le.fit_transform(dis_sym_data_v1[col])

# Split data into features and target
X = dis_sym_data_v1.drop(columns="Disease")
y = dis_sym_data_v1['Disease']

# Define a function to train models and save them
def class_algo(model, independent, dependent, model_name):
    model.fit(independent, dependent)
    pred = model.predict(independent)
    accuracy = metrics.accuracy_score(pred, dependent)
    print(f"{model_name} Accuracy: {accuracy:.3%}")
    model_filename = f"{model.__class__.__name__}_model.pkl"
    joblib.dump(model, model_filename)  # Save the model to a file
    print(f"Model saved as {model_filename}\n")

# Define algorithms
algorithms = {
    'Logistic Regression': {"model": LogisticRegression()},
    'Decision Tree': {"model": tree.DecisionTreeClassifier()},
    'Random Forest': {"model": RandomForestClassifier()},
    'SVM': {"model": svm.SVC(probability=True)},
    'Naive Bayes': {"model": GaussianNB()},
    'K-Nearest Neighbors': {"model": KNeighborsClassifier()},
}

# Train and save models
for model_name, values in algorithms.items():
    class_algo(values["model"], X, y, model_name)

Logistic Regression Accuracy: 99.978%
Model saved as LogisticRegression_model.pkl

Decision Tree Accuracy: 99.978%
Model saved as DecisionTreeClassifier_model.pkl

Random Forest Accuracy: 99.978%
Model saved as RandomForestClassifier_model.pkl

SVM Accuracy: 99.868%
Model saved as SVC_model.pkl

Naive Bayes Accuracy: 99.956%
Model saved as GaussianNB_model.pkl

K-Nearest Neighbors Accuracy: 99.912%
Model saved as KNeighborsClassifier_model.pkl

In [31]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
import joblib

# Load the dataset
pd.set_option('display.max_colwidth', None)
dis_sym_data = pd.read_csv(r"Original_Dataset.csv")

# Ensure column names are strings to avoid errors
dis_sym_data.columns = dis_sym_data.columns.astype(str)

# Generate binary features for symptoms
columns_to_check = [col for col in dis_sym_data.columns if col != 'Disease']

# Flatten symptoms, deduplicate, and create binary features
symptoms = dis_sym_data.iloc[:, 1:].values.flatten()
symptoms = list(set(symptoms[~pd.isnull(symptoms)]))  # Remove NaN values

for symptom in symptoms:
    dis_sym_data[symptom] = dis_sym_data.iloc[:, 1:].apply(
        lambda row: int(symptom in row.values), axis=1
    )

# Drop original symptom columns to keep only binary features
dis_sym_data_v1 = dis_sym_data.drop(columns=columns_to_check)

# Ensure no NaN column names exist
dis_sym_data_v1 = dis_sym_data_v1.loc[:, dis_sym_data_v1.columns.notna()]

# Strip whitespace from column names
dis_sym_data_v1.columns = dis_sym_data_v1.columns.str.strip()

# Encode the target variable
var_mod = ['Disease']
le = LabelEncoder()
for col in var_mod:
    dis_sym_data_v1[col] = le.fit_transform(dis_sym_data_v1[col])

# Save the LabelEncoder for later use
joblib.dump(le, "label_encoder.pkl")
print("LabelEncoder saved as 'label_encoder.pkl'")

# Split data into features and target
X = dis_sym_data_v1.drop(columns="Disease")
y = dis_sym_data_v1['Disease']

# Define a function to train models
def train_and_save_models(models, X, y):
    trained_algorithms = {}

    for model_name, model_info in models.items():
        model = model_info["model"]
        model.fit(X, y)
        pred = model.predict(X)
        accuracy = metrics.accuracy_score(pred, y)
        print(f"{model_name} Accuracy: {accuracy:.3%}")
        trained_algorithms[model_name] = {"model": model, "accuracy": accuracy}

    # Save all trained models to a single file
    joblib.dump(trained_algorithms, "trained_algorithms.pkl")
    print("All trained algorithms saved as 'trained_algorithms.pkl'")

# Define algorithms
algorithms = {
    'Logistic Regression': {"model": LogisticRegression(max_iter=1000)},
    'Decision Tree': {"model": tree.DecisionTreeClassifier()},
    'Random Forest': {"model": RandomForestClassifier()},
    'SVM': {"model": svm.SVC(probability=True)},
    'Naive Bayes': {"model": GaussianNB()},
    'K-Nearest Neighbors': {"model": KNeighborsClassifier()},
}

# Train and save all models
train_and_save_models(algorithms, X, y)

LabelEncoder saved as 'label_encoder.pkl'
Logistic Regression Accuracy: 99.978%
Decision Tree Accuracy: 99.978%
Random Forest Accuracy: 99.978%
SVM Accuracy: 99.868%
Naive Bayes Accuracy: 99.956%
K-Nearest Neighbors Accuracy: 99.912%
All trained algorithms saved as 'trained_algorithms.pkl'

In [32]:
doc_data = pd.read_csv(r"Doctor_Versus_Disease.csv",encoding='latin1', names=['Disease','Specialist'])

In [33]:
doc_data

                                    Disease           Specialist
0                             Drug Reaction            Allergist
1                                   Allergy            Allergist
2                             Hypertension          Cardiologist
3                              Heart attack         Cardiologist
4                                 Psoriasis        Dermatologist
5                               Chicken pox        Dermatologist
6                                      Acne        Dermatologist
7                                  Impetigo        Dermatologist
8                          Fungal infection        Dermatologist
9                            Hypothyroidism      Endocrinologist
10                                Diabetes       Endocrinologist
11                             Hypoglycemia      Endocrinologist
12                          Hyperthyroidism      Endocrinologist
13                                     GERD   Gastroenterologist
14                      Peptic ulcer diseae   Gastroenterologist
15                                 Jaundice   Gastroenterologist
16             Dimorphic hemmorhoids(piles)  Gastroenterologist
17                          Gastroenteritis   Gastroenterologist
18                  Urinary tract infection         Gynecologist
19                      Chronic cholestasis         Hepatologist
20                              hepatitis A         Hepatologist
21                              Hepatitis B         hepatologist
22                              Hepatitis C         Hepatologist
23                              Hepatitis E         Hepatologist
24                              Hepatitis D         Hepatologist
25                      Alcoholic hepatitis         Hepatologist
26                                  Malaria     Internal Medcine
27                                   Dengue     Internal Medcine
28                                 Migraine          Neurologist
29                     Cervical spondylosis          Neurologist
30             Paralysis (brain hemorrhage)          Neurologist
31                                     AIDS          Osteopathic
32  (vertigo) Paroymsal  Positional Vertigo     Otolaryngologist
33                              Common Cold     Otolaryngologist
34                                  Typhoid         Pediatrician
35                           Varicose veins         Phlebologist
36                         Bronchial Asthma        Pulmonologist
37                                Pneumonia        Pulmonologist
38                          Osteoarthristis      Rheumatologists
39                                Arthritis      Rheumatologists
40                             Tuberculosis         Tuberculosis

In [34]:
doc_data1= pd.read_csv(r"Doctor_Versus_Disease.csv",encoding='latin1', names=['Disease'])

In [35]:
doc_data1

                                                     Disease
Drug Reaction                                      Allergist
Allergy                                            Allergist
Hypertension                                    Cardiologist
Heart attack                                    Cardiologist
Psoriasis                                      Dermatologist
Chicken pox                                    Dermatologist
Acne                                           Dermatologist
Impetigo                                       Dermatologist
Fungal infection                               Dermatologist
Hypothyroidism                               Endocrinologist
Diabetes                                     Endocrinologist
Hypoglycemia                                 Endocrinologist
Hyperthyroidism                              Endocrinologist
GERD                                      Gastroenterologist
Peptic ulcer diseae                       Gastroenterologist
Jaundice                                  Gastroenterologist
Dimorphic hemmorhoids(piles)             Gastroenterologist
Gastroenteritis                           Gastroenterologist
Urinary tract infection                         Gynecologist
Chronic cholestasis                             Hepatologist
hepatitis A                                     Hepatologist
Hepatitis B                                     hepatologist
Hepatitis C                                     Hepatologist
Hepatitis E                                     Hepatologist
Hepatitis D                                     Hepatologist
Alcoholic hepatitis                             Hepatologist
Malaria                                     Internal Medcine
Dengue                                      Internal Medcine
Migraine                                         Neurologist
Cervical spondylosis                             Neurologist
Paralysis (brain hemorrhage)                     Neurologist
AIDS                                             Osteopathic
(vertigo) Paroymsal  Positional Vertigo     Otolaryngologist
Common Cold                                 Otolaryngologist
Typhoid                                         Pediatrician
Varicose veins                                  Phlebologist
Bronchial Asthma                               Pulmonologist
Pneumonia                                      Pulmonologist
Osteoarthristis                              Rheumatologists
Arthritis                                    Rheumatologists
Tuberculosis                                    Tuberculosis

In [36]:
import numpy as np
doc_data['Specialist'] = np.where((doc_data['Disease'] == 'Tuberculosis'),'Pulmonologist', doc_data['Specialist'])

In [37]:
des_data = pd.read_csv(r"Disease_Description.csv")

In [38]:
des_data

,Disease,Description
0,Drug Reaction,An adverse drug reaction (ADR) is an injury caused by taking medication. ADRs may occur following a single dose or prolonged administration of a drug or result from the combination of two or more drugs.
1,Malaria,An infectious disease caused by protozoan parasites from the Plasmodium family that can be transmitted by the bite of the Anopheles mosquito or by a contaminated needle or transfusion. Falciparum malaria is the most deadly type.
2,Allergy,"An allergy is an immune system response to a foreign substance that's not typically harmful to your body.They can include certain foods, pollen, or pet dander. Your immune system's job is to keep you healthy by fighting harmful pathogens."
3,Hypothyroidism,"Hypothyroidism, also called underactive thyroid or low thyroid, is a disorder of the endocrine system in which the thyroid gland does not produce enough thyroid hormone."
4,Psoriasis,"Psoriasis is a common skin disorder that forms thick, red, bumpy patches covered with silvery scales. They can pop up anywhere, but most appear on the scalp, elbows, knees, and lower back. Psoriasis can't be passed from person to person. It does sometimes happen in members of the same family."
5,GERD,"Gastroesophageal reflux disease, or GERD, is a digestive disorder that affects the lower esophageal sphincter (LES), the ring of muscle between the esophagus and stomach. Many people, including pregnant women, suffer from heartburn or acid indigestion caused by GERD."
6,Chronic cholestasis,"Chronic cholestatic diseases, whether occurring in infancy, childhood or adulthood, are characterized by defective bile acid transport from the liver to the intestine, which is caused by primary damage to the biliary epithelium in most cases"
7,hepatitis A,Hepatitis A is a highly contagious liver infection caused by the hepatitis A virus. The virus is one of several types of hepatitis viruses that cause inflammation and affect your liver's ability to function.
8,Osteoarthristis,"Osteoarthritis is the most common form of arthritis, affecting millions of people worldwide. It occurs when the protective cartilage that cushions the ends of your bones wears down over time."
9,(vertigo) Paroymsal Positional Vertigo,Benign paroxysmal positional vertigo (BPPV) is one of the most common causes of vertigo — the sudden sensation that you're spinning or that the inside of your head is spinning. Benign paroxysmal positional vertigo causes brief episodes of mild to intense dizziness.
10,Hypoglycemia,Hypoglycemia is a condition in which your blood sugar (glucose) level is lower than normal. Glucose is your body's main energy source. Hypoglycemia is often related to diabetes treatment. But other drugs and a variety of conditions — many rare — can cause low blood sugar in people who don't have diabetes.
11,Acne,"Acne vulgaris is the formation of comedones, papules, pustules, nodules, and/or cysts as a result of obstruction and inflammation of pilosebaceous units (hair follicles and their accompanying sebaceous gland). Acne develops on the face and upper trunk. It most often affects adolescents."
12,Diabetes,"Diabetes is a disease that occurs when your blood glucose, also called blood sugar, is too high. Blood glucose is your main source of energy and comes from the food you eat. Insulin, a hormone made by the pancreas, helps glucose from food get into your cells to be used for energy."
13,Impetigo,"Impetigo (im-puh-TIE-go) is a common and highly contagious skin infection that mainly affects infants and children. Impetigo usually appears as red sores on the face, especially around a child's nose and mouth, and on hands and feet. The sores burst and develop honey-colored crusts."
14,Hypertension,"Hypertension (HTN or HT), also known as high blood pressure (HBP), is a long-term medical condition in which the blood pressure in the arteries is persistently elevated. High blood pressure typically does not cause symptoms."
15,Peptic ulcer diseae,"Peptic ulcer disease (PUD) is a break in the inner lining of the stomach, the first part of the small intestine, or sometimes the lower esophagus. An ulcer in the stomach is called a gastric ulcer, while one in the first part of the intestines is a duodenal ulcer."
16,Dimorphic hemorrhoids(piles),"Hemorrhoids, also spelled haemorrhoids, are vascular structures in the anal canal. In their ... Other names, Haemorrhoids, piles, hemorrhoidal disease ."
17,Common Cold,"The common cold is a viral infection of your nose and throat (upper respiratory tract). It's usually harmless, although it might not feel that way. Many types of viruses can cause a common cold."
18,Chicken pox,"Chickenpox is a highly contagious disease caused by the varicella-zoster virus (VZV). It can cause an itchy, blister-like rash. The rash first appears on the chest, back, and face, and then spreads over the entire body, causing between 250 and 500 itchy blisters."
19,Cervical spondylosis,"Cervical spondylosis is a general term for age-related wear and tear affecting the spinal disks in your neck. As the disks dehydrate and shrink, signs of osteoarthritis develop, including bony projections along the edges of bones (bone spurs)."
20,Hyperthyroidism,"Hyperthyroidism (overactive thyroid) occurs when your thyroid gland produces too much of the hormone thyroxine. Hyperthyroidism can accelerate your body's metabolism, causing unintentional weight loss and a rapid or irregular heartbeat."
21,Urinary tract infection,"Urinary tract infection: An infection of the kidney, ureter, bladder, or urethra. Abbreviated UTI. Not everyone with a UTI has symptoms, but common symptoms include a frequent urge to urinate and pain or burning when urinating."
22,Varicose veins,"A vein that has enlarged and twisted, often appearing as a bulging, blue blood vessel that is clearly visible through the skin. Varicose veins are most common in older adults, particularly women, and occur especially on the legs."
23,AIDS,"Acquired immunodeficiency syndrome (AIDS) is a chronic, potentially life-threatening condition caused by the human immunodeficiency virus (HIV). By damaging your immune system, HIV interferes with your body's ability to fight infection and disease."
24,Paralysis (brain hemorrhage),"Intracerebral hemorrhage (ICH) is when blood suddenly bursts into brain tissue, causing damage to your brain. Symptoms usually appear suddenly during ICH. They include headache, weakness, confusion, and paralysis, particularly on one side of your body."
25,Typhoid,"An acute illness characterized by fever caused by infection with the bacterium Salmonella typhi. Typhoid fever has an insidious onset, with fever, headache, constipation, malaise, chills, and muscle pain. Diarrhea is uncommon, and vomiting is not usually severe."
26,Hepatitis B,"Hepatitis B is an infection of your liver. It can cause scarring of the organ, liver failure, and cancer. It can be fatal if it isn't treated. It's spread when people come in contact with the blood, open sores, or body fluids of someone who has the hepatitis B virus."
27,Fungal infection,"In humans, fungal infections occur when an invading fungus takes over an area of the body and is too much for the immune system to handle. Fungi can live in the air, soil, water, and plants. There are also some fungi that live naturally in the human body. Like many microbes, there are helpful fungi and harmful fungi."
28,Hepatitis C,"Inflammation of the liver due to the hepatitis C virus (HCV), which is usually spread via blood transfusion (rare), hemodialysis, and needle sticks. The damage hepatitis C does to the liver can lead to cirrhosis and its complications as well as cancer."
29,Migraine,"A migraine can cause severe throbbing pain or a pulsing sensation, usually on one side of the head. It's often accompanied by nausea, vomiting, and extreme sensitivity to light and sound. Migraine attacks can last for hours to days, and the pain can be so severe that it interferes with your daily activities."
30,Bronchial Asthma,"Bronchial asthma is a medical condition which causes the airway path of the lungs to swell and narrow. Due to this swelling, the air path produces excess mucus making it hard to breathe, which results in coughing, short breath, and wheezing. The disease is chronic and interferes with daily working."
31,Alcoholic hepatitis,"Alcoholic hepatitis is a diseased, inflammatory condition of the liver caused by heavy alcohol consumption over an extended period of time. It's also aggravated by binge drinking and ongoing alcohol use. If you develop this condition, you must stop drinking alcohol"
32,Jaundice,"Yellow staining of the skin and sclerae (the whites of the eyes) by abnormally high blood levels of the bile pigment bilirubin. The yellowing extends to other tissues and body fluids. Jaundice was once called the ""morbus regius"" (the regal disease) in the belief that only the touch of a king could cure it"
33,Hepatitis E,A rare form of liver inflammation caused by infection with the hepatitis E virus (HEV). It is transmitted via food or drink handled by an infected person or through infected water supplies in areas where fecal matter may get into the water. Hepatitis E does not cause chronic liver disease.
34,Dengue,"an acute infectious disease caused by a flavivirus (species Dengue virus of the genus Flavivirus), transmitted by aedes mosquitoes, and characterized by headache, severe joint pain, and a rash. — called also breakbone fever, dengue fever."
35,Hepatitis D,"Hepatitis D, also known as the hepatitis delta virus, is an infection that causes the liver to become inflamed. This swelling can impair liver function and cause long-term liver problems, including liver scarring and cancer. The condition is caused by the hepatitis D virus (HDV)."
36,Heart attack,"The death of heart muscle due to the loss of blood supply. The loss of blood supply is usually caused by a complete blockage of a coronary artery, one of the arteries that supplies blood to the heart muscle."
37,Pneumonia,"Pneumonia is an infection in one or both lungs. Bacteria, viruses, and fungi cause it. The infection causes inflammation in the air sacs in your lungs, which are called alveoli. The alveoli fill with fluid or pus, making it difficult to breathe."
38,Arthritis,"Arthritis is the swelling and tenderness of one or more of your joints. The main symptoms of arthritis are joint pain and stiffness, which typically worsen with age. The most common types of arthritis are osteoarthritis and rheumatoid arthritis."
39,Gastroenteritis,"Gastroenteritis is an inflammation of the digestive tract, particularly the stomach, and large and small intestines. Viral and bacterial gastroenteritis are intestinal infections associated with symptoms of diarrhea , abdominal cramps, nausea , and vomiting ."
40,Tuberculosis,"Tuberculosis (TB) is an infectious disease usually caused by Mycobacterium tuberculosis (MTB) bacteria. Tuberculosis generally affects the lungs, but can also affect other parts of the body. Most infections show no symptoms, in which case it is known as latent tuberculosis."

In [39]:
des_data["Disease"]

0                               Drug Reaction
1                                     Malaria
2                                     Allergy
3                              Hypothyroidism
4                                   Psoriasis
5                                        GERD
6                         Chronic cholestasis
7                                 hepatitis A
8                             Osteoarthristis
9     (vertigo) Paroymsal  Positional Vertigo
10                               Hypoglycemia
11                                       Acne
12                                   Diabetes
13                                   Impetigo
14                               Hypertension
15                        Peptic ulcer diseae
16               Dimorphic hemorrhoids(piles)
17                                Common Cold
18                                Chicken pox
19                       Cervical spondylosis
20                            Hyperthyroidism
21                    Urinary tract infection
22                             Varicose veins
23                                       AIDS
24               Paralysis (brain hemorrhage)
25                                    Typhoid
26                                Hepatitis B
27                           Fungal infection
28                                Hepatitis C
29                                   Migraine
30                           Bronchial Asthma
31                        Alcoholic hepatitis
32                                   Jaundice
33                                Hepatitis E
34                                     Dengue
35                                Hepatitis D
36                               Heart attack
37                                  Pneumonia
38                                  Arthritis
39                            Gastroenteritis
40                               Tuberculosis
Name: Disease, dtype: object

In [40]:
### from collections import Counter
test_col = []
for col in dis_sym_data_v1.columns:
    if col != 'Disease':
        test_col.append(col)
print(test_col)

test_data = {}
symptoms = []
predicted = []
from collections import Counter
import pandas as pd
import joblib

# Load trained models and label encoder
trained_algorithms = joblib.load("trained_algorithms.pkl")
le = joblib.load("label_encoder.pkl")

def test_input():
    symptoms = []
    predicted = []
    
    num_inputs = int(input("Enter the number of symptoms you have: "))
    for i in range(num_inputs):
        user_input = input(f"Enter Symptoms #{i+1}: ").strip().replace(" ", "_").lower()
        symptoms.append(user_input)

    print("\nSymptoms you have:", symptoms)

    # Create test data dictionary
    test_data = {col: 1 if col in symptoms else 0 for col in X.columns}

    # Convert to DataFrame and align columns
    test_df = pd.DataFrame([test_data])
    test_df = test_df.reindex(columns=X.columns, fill_value=0)  # Ensure same feature set

    print("\nPredicting Disease based on 6 ML algorithms...\n")

    for model_name, values in trained_algorithms.items():
        model = values["model"]
        predict_disease = model.predict(test_df)
        predict_disease = le.inverse_transform(predict_disease)
        predicted.extend(predict_disease)

    # Calculate probabilities
    disease_counts = Counter(predicted)
    percentage_per_disease = {disease: (count / 6) * 100 for disease, count in disease_counts.items()}
    
    # Convert to DataFrame
    result_df = pd.DataFrame({
        "Disease": list(percentage_per_disease.keys()),
        "Chances": list(percentage_per_disease.values())
    })

    print(result_df)

# Run the test input function
test_input()

['dark_urine', 'weight_loss', 'blackheads', 'coma', 'yellowing_of_eyes', 'movement_stiffness', 'rusty_sputum', 'swollen_extremeties', 'swelled_lymph_nodes', 'swelling_of_stomach', 'phlegm', 'mild_fever', 'sunken_eyes', 'nausea', 'watering_from_eyes', 'stomach_pain', 'pain_in_anal_region', 'abnormal_menstruation', 'mucoid_sputum', 'swollen_legs', 'brittle_nails', 'silver_like_dusting', 'enlarged_thyroid', 'depression', 'inflammatory_nails', 'distention_of_abdomen', 'bladder_discomfort', 'receiving_blood_transfusion', 'puffy_face_and_eyes', 'visual_disturbances', 'abdominal_pain', 'headache', 'pain_behind_the_eyes', 'acute_liver_failure', 'weakness_of_one_body_side', 'cough', 'unsteadiness', 'skin_peeling', 'fluid_overload', 'fatigue', 'lethargy', 'diarrhoea', 'irregular_sugar_level', 'continuous_feel_of_urine', 'cramps', 'yellow_urine', 'sinus_pressure', 'vomiting', 'scurring', 'anxiety', 'increased_appetite', 'mood_swings', 'family_history', 'extra_marital_contacts', 'foul_smell_of urine', 'stiff_neck', 'slurred_speech', 'red_sore_around_nose', 'loss_of_smell', 'breathlessness', 'drying_and_tingling_lips', 'muscle_weakness', 'loss_of_balance', 'palpitations', 'high_fever', 'restlessness', 'muscle_pain', 'skin_rash', 'swelling_joints', 'irritability', 'itching', 'runny_nose', 'lack_of_concentration', 'spotting_ urination', 'indigestion', 'belly_pain', 'fever', 'joint_pain', 'blurred_and_distorted_vision', 'weight_gain', 'yellow_crust_ooze', 'stomach_bleeding', 'acidity', 'bloody_stool', 'knee_pain', 'neck_pain', 'throat_irritation', 'chills', 'spinning_movements', 'passage_of_gases', 'sweating', 'dischromic _patches', 'hip_joint_pain', 'burning_micturition', 'blood_in_sputum', 'toxic_look_(typhos)', 'ulcers_on_tongue', 'receiving_unsterile_injections', 'cold_hands_and_feets', 'irritation_in_anus', 'redness_of_eyes', 'continuous_sneezing', 'internal_itching', 'prominent_veins_on_calf', 'yellowish_skin', 'nodal_skin_eruptions', 'shivering', 'obesity', 'chest_pain', 'pus_filled_pimples', 'altered_sensorium', 'dizziness', 'swollen_blood_vessels', 'loss_of_appetite', 'patches_in_throat', 'history_of_alcohol_consumption', 'pain_during_bowel_movements', 'malaise', 'muscle_wasting', 'painful_walking', 'red_spots_over_body', 'fast_heart_rate', 'weakness_in_limbs', 'dehydration', 'excessive_hunger', 'blister', 'bruising', 'small_dents_in_nails', 'polyuria', 'back_pain', 'congestion', 'constipation']

Enter the number of symptoms you have:  3
Enter Symptoms #1:  blister
Enter Symptoms #2:  malaise
Enter Symptoms #3:  chest_pain

Symptoms you have: ['blister', 'malaise', 'chest_pain']

Predicting Disease based on 6 ML algorithms...

        Disease    Chances
0  Heart attack  50.000000
1   Chicken pox  16.666667
2      Impetigo  16.666667
3  Tuberculosis  16.666667

In [41]:
test_input()

Enter the number of symptoms you have:  3
Enter Symptoms #1:  cold
Enter Symptoms #2:  cough
Enter Symptoms #3:  chills

Symptoms you have: ['cold', 'cough', 'chills']

Predicting Disease based on 6 ML algorithms...

        Disease    Chances
0       Malaria  50.000000
1        Dengue  33.333333
2  Tuberculosis  16.666667

In [42]:
pip install gradio

Requirement already satisfied: gradio in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (5.23.1)
Requirement already satisfied: aiofiles<24.0,>=22.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (23.2.1)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (4.9.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.115.12)
Requirement already satisfied: ffmpy in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.5.0)
Requirement already satisfied: gradio-client==1.8.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (1.8.0)
Requirement already satisfied: groovy~=0.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx>=0.24.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.28.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.29.3)
Requirement already satisfied: jinja2<4.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (2.1.3)
Requirement already satisfied: orjson~=3.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (3.10.16)
Requirement already satisfied: packaging in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (24.2)
Requirement already satisfied: pandas<3.0,>=1.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (2.2.3)
Requirement already satisfied: pillow<12.0,>=8.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (11.1.0)
Requirement already satisfied: pydantic>=2.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (2.10.6)
Requirement already satisfied: pydub in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.0.20)
Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (6.0.2)
Requirement already satisfied: ruff>=0.9.3 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.11.2)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.1.6)
Requirement already satisfied: semantic-version~=2.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.46.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.13.2)
Requirement already satisfied: typer<1.0,>=0.12 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.15.2)
Requirement already satisfied: typing-extensions~=4.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (4.12.2)
Requirement already satisfied: uvicorn>=0.14.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio) (0.34.0)
Requirement already satisfied: fsspec in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio-client==1.8.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=10.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from gradio-client==1.8.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: certifi in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from httpx>=0.24.1->gradio) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from httpx>=0.24.1->gradio) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from huggingface-hub>=0.28.1->gradio) (3.18.0)
Requirement already satisfied: requests in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from huggingface-hub>=0.28.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from huggingface-hub>=0.28.1->gradio) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from pandas<3.0,>=1.0->gradio) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from pandas<3.0,>=1.0->gradio) (2025.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from pydantic>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from pydantic>=2.0->gradio) (2.27.2)
Requirement already satisfied: click>=8.0.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from typer<1.0,>=0.12->gradio) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: colorama in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from click>=8.0.0->typer<1.0,>=0.12->gradio) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.19.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from requests->huggingface-hub>=0.28.1->gradio) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from requests->huggingface-hub>=0.28.1->gradio) (2.3.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\abhishek\.conda\envs\chatbotenv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [43]:
import gradio as gr
import pandas as pd
from collections import Counter

# Assume `dis_sym_data_v1`, `doc_data`, `des_data`, `algorithms`, and `le` are preloaded or defined elsewhere

# Column names excluding 'Disease'
test_col = [col for col in dis_sym_data_v1.columns if col != 'Disease']

# Store chatbot state globally
symptoms = []
num_symptoms = 0
current_step = 0

def reset_state():
    global symptoms, num_symptoms, current_step
    symptoms = []
    num_symptoms = 0
    current_step = 0

# Function to predict disease once all symptoms are gathered
def predict_disease_chatbot():
    test_data = {}
    predicted = []

    # Prepare test data for prediction
    for column in test_col:
        test_data[column] = 1 if column in symptoms else 0
    test_df = pd.DataFrame(test_data, index=[0])

    # Predict using multiple algorithms and collect predictions
    for model_name, values in algorithms.items():
        predict_disease = values["model"].predict(test_df)
        predict_disease = le.inverse_transform(predict_disease)
        predicted.extend(predict_disease)

    # Calculate the chances of each predicted disease
    disease_counts = Counter(predicted)
    percentage_per_disease = {disease: (count / 6) * 100 for disease, count in disease_counts.items()}

    # Convert to DataFrame
    result_df = pd.DataFrame({"Disease": list(percentage_per_disease.keys()),
                              "Chances": list(percentage_per_disease.values())})

    # Merge additional information (doctor and description)
    result_df = result_df.merge(doc_data, on='Disease', how='left')
    result_df = result_df.merge(des_data, on='Disease', how='left')

    # Format the response
    response = "Here are the predictions based on your symptoms:\n"
    for index, row in result_df.iterrows():
        doctor_info = row.get('Doctor', 'Doctor info not available')
        description_info = row.get('Description', 'Description not available')
        response += f"Disease: {row['Disease']}\nChances: {row['Chances']:.2f}%\nDoctor: {doctor_info}\nDescription: {description_info}\n\n"
    
    reset_state()  # Reset state after prediction
    return response

# Function to handle user inputs step by step, while maintaining the chat history
def chatbot_interface(user_input, chat_history=[]):
    global symptoms, num_symptoms, current_step

    if current_step == 0:
        # Step 1: Ask how many symptoms the user has
        try:
            num_symptoms = int(user_input)
            current_step = 1
            response = f"Okay, you have {num_symptoms} symptoms. Please enter symptom #1."
        except ValueError:
            response = "Please enter a valid number of symptoms."

    elif current_step <= num_symptoms:
        # Step 2: Collect symptoms one by one
        symptoms.append(user_input)
        if current_step < num_symptoms:
            current_step += 1
            response = f"Please enter symptom #{current_step}."
        else:
            # Step 3: Make the prediction
            response = predict_disease_chatbot()

    # Append the user input and chatbot response to the chat history
    chat_history.append((f"User: {user_input}", f"Chatbot: {response}"))
    
    return chat_history, chat_history  # Return the updated chat history and state

# Gradio chatbot interface with a submit button
iface = gr.Interface(
    fn=chatbot_interface,
    inputs=[gr.Textbox(label="Enter your message", placeholder="Please Enter How many symptoms you have....", lines=1), gr.State([])],  # Textbox input and chat history state
    outputs=[gr.Chatbot(), gr.State([])],  # Output chatbot conversation and chat history state
    title="Disease Prediction Chatbot",
    description="Chatbot to predict possible diseases based on symptoms. First, enter the number of symptoms, and then enter each symptom one by one.",
    allow_flagging="never"
)

# Launch the chatbot interface
iface.launch()

* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

In [44]:
import gradio as gr
import pandas as pd
from collections import Counter
import joblib  # Import joblib for loading the saved models

# Assume the following files for the models:
model_files = {
    'Logistic Regression': 'LogisticRegression_model.pkl',
    'Decision Tree': 'DecisionTreeClassifier_model.pkl',
    'Random Forest': 'RandomForestClassifier_model.pkl',
    'SVM': 'SVC_model.pkl',
    'NaiveBayes': 'GaussianNB_model.pkl',
    'K-Nearest Neighbors': 'KNeighborsClassifier_model.pkl'
}

# Load the models from .pkl files
algorithms = {}
for model_name, model_file in model_files.items():
    algorithms[model_name] = {"model": joblib.load(model_file)}

# Assuming `dis_sym_data_v1`, `doc_data`, `des_data`, and `le` are preloaded or defined elsewhere

# Column names excluding 'Disease'
test_col = [col for col in dis_sym_data_v1.columns if col != 'Disease']

# Store chatbot state globally
symptoms = []
num_symptoms = 0
current_step = 0

def reset_state():
    global symptoms, num_symptoms, current_step
    symptoms = []
    num_symptoms = 0
    current_step = 0

# Function to predict disease once all symptoms are gathered
def predict_disease_chatbot():
    test_data = {}
    predicted = []

    # Prepare test data for prediction
    for column in test_col:
        test_data[column] = 1 if column in symptoms else 0
    test_df = pd.DataFrame(test_data, index=[0])
    print(test_df)
    # Predict using multiple algorithms and collect predictions
    for model_name, values in algorithms.items():
        predict_disease = values["model"].predict(test_df)
        predict_disease = le.inverse_transform(predict_disease)
        predicted.extend(predict_disease)
    
    # Calculate the chances of each predicted disease
    disease_counts = Counter(predicted)
    percentage_per_disease = {disease: (count / 6) * 100 for disease, count in disease_counts.items()}

    # Convert to DataFrame
    result_df = pd.DataFrame({"Disease": list(percentage_per_disease.keys()),
                              "Chances": list(percentage_per_disease.values())})

    # Merge additional information (doctor and description)
    result_df = result_df.merge(doc_data, on='Disease', how='left')
    result_df = result_df.merge(des_data, on='Disease', how='left')

    # Format the response
    response = "Here are the predictions based on your symptoms:\n"
    for index, row in result_df.iterrows():
        doctor_info = row.get('Doctor', 'Doctor info not available')
        description_info = row.get('Description', 'Description not available')
        response += f"Disease: {row['Disease']}\nChances: {row['Chances']:.2f}%\nDoctor: {doctor_info}\nDescription: {description_info}\n\n"
    
    reset_state()  # Reset state after prediction
    return response

# Function to handle user inputs step by step, while maintaining the chat history
def chatbot_interface(user_input, chat_history=[]):
    global symptoms, num_symptoms, current_step

    if current_step == 0:
        # Step 1: Ask how many symptoms the user has
        try:
            num_symptoms = int(user_input)
            current_step = 1
            response = f"Okay, you have {num_symptoms} symptoms. Please enter symptom #1."
        except ValueError:
            response = "Please enter a valid number of symptoms."

    elif current_step <= num_symptoms:
        # Step 2: Collect symptoms one by one
        symptoms.append(user_input)
        if current_step < num_symptoms:
            current_step += 1
            response = f"Please enter symptom #{current_step}."
        else:
            # Step 3: Make the prediction
            response = predict_disease_chatbot()

    # Append the user input and chatbot response to the chat history
    chat_history.append((f"User: {user_input}", f"Chatbot: {response}"))
    
    return chat_history, chat_history  # Return the updated chat history and state

# Gradio chatbot interface with a submit button
iface = gr.Interface(
    fn=chatbot_interface,
    inputs=[gr.Textbox(label="Enter your message", placeholder="Please Enter How many symptoms you have....", lines=1), gr.State([])],  # Textbox input and chat history state
    outputs=[gr.Chatbot(), gr.State([])],  # Output chatbot conversation and chat history state
    title="Disease Prediction Chatbot",
    description="Chatbot to predict possible diseases based on symptoms. First, enter the number of symptoms, and then enter each symptom one by one.",
    allow_flagging="never"
)

# Launch the chatbot interface
iface.launch()

* Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.

In [45]:
import gradio as gr
import pandas as pd
from collections import Counter

# Assume `dis_sym_data_v1`, `doc_data`, `des_data`, `algorithms`, and `le` are preloaded or defined elsewhere

# Column names excluding 'Disease'
test_col = [col for col in dis_sym_data_v1.columns if col != 'Disease']

# Store chatbot state globally
symptoms = []
num_symptoms = 0
current_step = 0

def reset_state():
    global symptoms, num_symptoms, current_step
    symptoms = []
    num_symptoms = 0
    current_step = 0

# Function to predict disease once all symptoms are gathered
def predict_disease_chatbot():
    test_data = {}
    predicted = []

    # Prepare test data for prediction
    for column in test_col:
        test_data[column] = 1 if column in symptoms else 0
    test_df = pd.DataFrame(test_data, index=[0])

    # Predict using multiple algorithms and collect predictions
    for model_name, values in algorithms.items():
        predict_disease = values["model"].predict(test_df)
        predict_disease = le.inverse_transform(predict_disease)
        predicted.extend(predict_disease)

    # Calculate the chances of each predicted disease
    disease_counts = Counter(predicted)
    percentage_per_disease = {disease: (count / len(algorithms)) * 100 for disease, count in disease_counts.items()}

    # Convert to DataFrame
    result_df = pd.DataFrame({"Disease": list(percentage_per_disease.keys()),
                              "Chances": list(percentage_per_disease.values())})

    # Merge additional information (specialist and description)
    result_df = result_df.merge(doc_data, on='Disease', how='left')
    result_df = result_df.merge(des_data, on='Disease', how='left')

    # Format the response
    response = "Here are the predictions based on your symptoms:\n"
    for index, row in result_df.iterrows():
        specialist_info = row.get('Specialist', 'Specialist info not available')
        description_info = row.get('Description', 'Description not available')
        response += f"Disease: {row['Disease']}\nChances: {row['Chances']:.2f}%\nSpecialist: {specialist_info}\nDescription: {description_info}\n\n"

    reset_state()  # Reset state after prediction
    return response

# Function to handle user inputs step by step, while maintaining the chat history
def chatbot_interface(user_input, chat_history=[]):
    global symptoms, num_symptoms, current_step

    if current_step == 0:
        # Step 1: Ask how many symptoms the user has
        try:
            num_symptoms = int(user_input)
            current_step = 1
            response = f"Okay, you have {num_symptoms} symptoms. Please enter symptom #1."
        except ValueError:
            response = "Please enter a valid number of symptoms."

    elif current_step <= num_symptoms:
        # Step 2: Collect symptoms one by one
        symptoms.append(user_input)
        if current_step < num_symptoms:
            current_step += 1
            response = f"Please enter symptom #{current_step}."
        else:
            # Step 3: Make the prediction
            response = predict_disease_chatbot()

    # Append the user input and chatbot response to the chat history
    chat_history.append((f"User: {user_input}", f"Chatbot: {response}"))
    
    return chat_history, chat_history  # Return the updated chat history and state

# Gradio chatbot interface with a submit button
iface = gr.Interface(
    fn=chatbot_interface,
    inputs=[gr.Textbox(label="Enter your message", placeholder="Please Enter How many symptoms you have....", lines=1), gr.State([])],  # Textbox input and chat history state
    outputs=[gr.Chatbot(), gr.State([])],  # Output chatbot conversation and chat history state
    title="Disease Prediction Chatbot",
    description="Chatbot to predict possible diseases based on symptoms. First, enter the number of symptoms, and then enter each symptom one by one.",
    allow_flagging="never"
)

# Launch the chatbot interface
iface.launch()

* Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.